package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Alerta generated by hbm2java
 */
@Entity
@NamedQueries({
	 @NamedQuery(name = "Alerta.findAll", query = "SELECT a FROM Alerta a ORDER BY a.titulo"),
	 @NamedQuery(name = "Alerta.countAll", query = "SELECT count(*) FROM Alerta a"),
})
@Table(name = "alerta", catalog = "itinerant_db")
public class Alerta implements java.io.Serializable {

	private int idAlerta;
	private UsuarioInterno usuarioInterno;
	private String titulo;
	private String cuerpo;

	public Alerta() {
	}

	public Alerta(int idAlerta, UsuarioInterno usuarioInterno, String titulo, String cuerpo) {
		this.idAlerta = idAlerta;
		this.usuarioInterno = usuarioInterno;
		this.titulo = titulo;
		this.cuerpo = cuerpo;
	}

	@Id
	@Column(name = "id_alerta", unique = true, nullable = false)
	public int getIdAlerta() {
		return this.idAlerta;
	}

	public void setIdAlerta(int idAlerta) {
		this.idAlerta = idAlerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public UsuarioInterno getUsuarioInterno() {
		return this.usuarioInterno;
	}

	public void setUsuarioInterno(UsuarioInterno usuarioInterno) {
		this.usuarioInterno = usuarioInterno;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "cuerpo", nullable = false, length = 100)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

}
