package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Alerta generated by hbm2java
 */
@Entity
@NamedQueries({
	 @NamedQuery(name = "Alerta.findAll", query = "SELECT a FROM Alerta a"),
	 @NamedQuery(name = "Alerta.findAllByLogin", query = "SELECT a FROM Alerta a WHERE a.usuarioInterno.login = :login"),
	 @NamedQuery(name = "Alerta.countAll", query = "SELECT count(*) FROM Alerta a"),
})
@Table(name = "alerta", catalog = "itinerant_db")
public class Alerta implements java.io.Serializable {

	private Integer idAlerta;
	private UsuarioInterno usuarioInterno;
	private String titulo;
	private String cuerpo;
	private boolean visto;
	private boolean nuevo;

	public Alerta() {
	}

	public Alerta(UsuarioInterno usuarioInterno, String titulo, String cuerpo) {
		this.usuarioInterno = usuarioInterno;
		this.titulo = titulo;
		this.cuerpo = cuerpo;
		this.visto = false;
		this.nuevo = true;
	}
	
	public Alerta(UsuarioInterno usuarioInterno, String titulo, String cuerpo, boolean visto) {
		this.usuarioInterno = usuarioInterno;
		this.titulo = titulo;
		this.cuerpo = cuerpo;
		this.visto = visto;
		this.nuevo = true;
	}
	
	public Alerta(UsuarioInterno usuarioInterno, String titulo, String cuerpo, boolean visto, boolean nuevo) {
		this.usuarioInterno = usuarioInterno;
		this.titulo = titulo;
		this.cuerpo = cuerpo;
		this.visto = visto;
		this.nuevo = nuevo;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alerta", unique = true, nullable = false)
	public Integer getIdAlerta() {
		return this.idAlerta;
	}

	public void setIdAlerta(Integer idAlerta) {
		this.idAlerta = idAlerta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public UsuarioInterno getUsuarioInterno() {
		return this.usuarioInterno;
	}

	public void setUsuarioInterno(UsuarioInterno usuarioInterno) {
		this.usuarioInterno = usuarioInterno;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "cuerpo", nullable = false, length = 500)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}
	
	@Column(name = "visto", nullable = false, length = 100)
	public boolean getVisto() {
		return this.visto;
	}

	public void setVisto(boolean visto) {
		this.visto = visto;
	}
	
	@Column(name = "nuevo", nullable = false, length = 100)
	public boolean getNuevo() {
		return this.nuevo;
	}

	public void setNuevo(boolean nuevo) {
		this.nuevo = nuevo;
	}

}
