package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Certificado generated by hbm2java
 */
@Entity
@Table(name = "certificado", catalog = "itinerant_db")
public class Certificado implements java.io.Serializable {

	private CertificadoId id;
	private Profesional profesional;
	private String entidadEmisora;
	private int anyo;
	private Byte validez;

	public Certificado() {
	}

	public Certificado(CertificadoId id, Profesional profesional, String entidadEmisora, int anyo) {
		this.id = id;
		this.profesional = profesional;
		this.entidadEmisora = entidadEmisora;
		this.anyo = anyo;
	}

	public Certificado(CertificadoId id, Profesional profesional, String entidadEmisora, int anyo, Byte validez) {
		this.id = id;
		this.profesional = profesional;
		this.entidadEmisora = entidadEmisora;
		this.anyo = anyo;
		this.validez = validez;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProfesional", column = @Column(name = "id_profesional", nullable = false, length = 30)),
			@AttributeOverride(name = "titulo", column = @Column(name = "titulo", nullable = false, length = 50)) })
	public CertificadoId getId() {
		return this.id;
	}

	public void setId(CertificadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_profesional", nullable = false, insertable = false, updatable = false)
	public Profesional getProfesional() {
		return this.profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	@Column(name = "entidad_emisora", nullable = false, length = 50)
	public String getEntidadEmisora() {
		return this.entidadEmisora;
	}

	public void setEntidadEmisora(String entidadEmisora) {
		this.entidadEmisora = entidadEmisora;
	}

	@Column(name = "anyo", nullable = false)
	public int getAnyo() {
		return this.anyo;
	}

	public void setAnyo(int anyo) {
		this.anyo = anyo;
	}

	@Column(name = "validez")
	public Byte getValidez() {
		return this.validez;
	}

	public void setValidez(Byte validez) {
		this.validez = validez;
	}

}
