package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertificadoId generated by hbm2java
 */
@Embeddable
public class CertificadoId implements java.io.Serializable {

	private String idProfesional;
	private String titulo;

	public CertificadoId() {
	}

	public CertificadoId(String idProfesional, String titulo) {
		this.idProfesional = idProfesional;
		this.titulo = titulo;
	}

	@Column(name = "id_profesional", nullable = false, length = 30)
	public String getIdProfesional() {
		return this.idProfesional;
	}

	public void setIdProfesional(String idProfesional) {
		this.idProfesional = idProfesional;
	}

	@Column(name = "titulo", nullable = false, length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CertificadoId))
			return false;
		CertificadoId castOther = (CertificadoId) other;

		return ((this.getIdProfesional() == castOther.getIdProfesional())
				|| (this.getIdProfesional() != null && castOther.getIdProfesional() != null
						&& this.getIdProfesional().equals(castOther.getIdProfesional())))
				&& ((this.getTitulo() == castOther.getTitulo()) || (this.getTitulo() != null
						&& castOther.getTitulo() != null && this.getTitulo().equals(castOther.getTitulo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfesional() == null ? 0 : this.getIdProfesional().hashCode());
		result = 37 * result + (getTitulo() == null ? 0 : this.getTitulo().hashCode());
		return result;
	}

}
