package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ChatMensaje generated by hbm2java
 */
@Entity
@NamedQueries({
	 @NamedQuery(name = "ChatMensaje.findAll", query = "SELECT m FROM ChatMensaje m"),
	 @NamedQuery(name = "ChatMensaje.countAll", query = "SELECT count(*) FROM ChatMensaje m"),
})
@Table(name = "chat_mensaje", catalog = "itinerant_db")
public class ChatMensaje implements java.io.Serializable {

	private ChatMensajeId id;
	private Chat chat;
	private String cuerpo;

	public ChatMensaje() {
	}

	public ChatMensaje(ChatMensajeId id, Chat chat, String cuerpo) {
		this.id = id;
		this.chat = chat;
		this.cuerpo = cuerpo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMensaje", column = @Column(name = "id_mensaje", nullable = false)),
			@AttributeOverride(name = "idChat", column = @Column(name = "id_chat", nullable = false)) })
	public ChatMensajeId getId() {
		return this.id;
	}

	public void setId(ChatMensajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chat", nullable = false, insertable = false, updatable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@Column(name = "cuerpo", nullable = false, length = 45)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

}
