package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatMensajeId generated by hbm2java
 */
@Embeddable
public class ChatMensajeId implements java.io.Serializable {

	private int idMensaje;
	private int idChat;

	public ChatMensajeId() {
	}

	public ChatMensajeId(int idMensaje, int idChat) {
		this.idMensaje = idMensaje;
		this.idChat = idChat;
	}

	@Column(name = "id_mensaje", nullable = false)
	public int getIdMensaje() {
		return this.idMensaje;
	}

	public void setIdMensaje(int idMensaje) {
		this.idMensaje = idMensaje;
	}

	@Column(name = "id_chat", nullable = false)
	public int getIdChat() {
		return this.idChat;
	}

	public void setIdChat(int idChat) {
		this.idChat = idChat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChatMensajeId))
			return false;
		ChatMensajeId castOther = (ChatMensajeId) other;

		return (this.getIdMensaje() == castOther.getIdMensaje()) && (this.getIdChat() == castOther.getIdChat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMensaje();
		result = 37 * result + this.getIdChat();
		return result;
	}

}
