package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CitaId generated by hbm2java
 */
@Embeddable
public class CitaId implements java.io.Serializable {

	private String idProfesional;
	private int idLocalidad;
	private Date fecha;
	private String idCiudadano;

	public CitaId() {
	}

	public CitaId(String idProfesional, int idLocalidad, Date fecha, String idCiudadano) {
		this.idProfesional = idProfesional;
		this.idLocalidad = idLocalidad;
		this.fecha = fecha;
		this.idCiudadano = idCiudadano;
	}

	@Column(name = "id_profesional", nullable = false, length = 30)
	public String getIdProfesional() {
		return this.idProfesional;
	}

	public void setIdProfesional(String idProfesional) {
		this.idProfesional = idProfesional;
	}

	@Column(name = "id_localidad", nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_ciudadano", nullable = false, length = 30)
	public String getIdCiudadano() {
		return this.idCiudadano;
	}

	public void setIdCiudadano(String idCiudadano) {
		this.idCiudadano = idCiudadano;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CitaId))
			return false;
		CitaId castOther = (CitaId) other;

		return ((this.getIdProfesional() == castOther.getIdProfesional())
				|| (this.getIdProfesional() != null && castOther.getIdProfesional() != null
						&& this.getIdProfesional().equals(castOther.getIdProfesional())))
				&& (this.getIdLocalidad() == castOther.getIdLocalidad())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getIdCiudadano() == castOther.getIdCiudadano())
						|| (this.getIdCiudadano() != null && castOther.getIdCiudadano() != null
								&& this.getIdCiudadano().equals(castOther.getIdCiudadano())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfesional() == null ? 0 : this.getIdProfesional().hashCode());
		result = 37 * result + this.getIdLocalidad();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getIdCiudadano() == null ? 0 : this.getIdCiudadano().hashCode());
		return result;
	}

}
