package com.itinerant.entity;
// Generated 10 nov 2022 18:51:10 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CitaId generated by hbm2java
 */
@Embeddable
public class CitaId implements java.io.Serializable {

	private int idVisita;
	private String idCiudadano;

	public CitaId() {
	}

	public CitaId(int idVisita, String idCiudadano) {
		this.idVisita = idVisita;
		this.idCiudadano = idCiudadano;
	}

	@Column(name = "id_visita", nullable = false)
	public int getIdVisita() {
		return this.idVisita;
	}

	public void setIdVisita(int idVisita) {
		this.idVisita = idVisita;
	}

	@Column(name = "id_ciudadano", nullable = false, length = 30)
	public String getIdCiudadano() {
		return this.idCiudadano;
	}

	public void setIdCiudadano(String idCiudadano) {
		this.idCiudadano = idCiudadano;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CitaId))
			return false;
		CitaId castOther = (CitaId) other;

		return (this.getIdVisita() == castOther.getIdVisita()) && ((this.getIdCiudadano() == castOther.getIdCiudadano())
				|| (this.getIdCiudadano() != null && castOther.getIdCiudadano() != null
						&& this.getIdCiudadano().equals(castOther.getIdCiudadano())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVisita();
		result = 37 * result + (getIdCiudadano() == null ? 0 : this.getIdCiudadano().hashCode());
		return result;
	}

}
