package com.itinerant.entity;
// Generated 26 ene 2023 10:48:55 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Jornada generated by hbm2java
 */
@Entity
@Table(name = "jornada", catalog = "itinerant_db")
public class Jornada implements java.io.Serializable {

	private JornadaId id;

	public Jornada() {
	}

	public Jornada(JornadaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProfesional", column = @Column(name = "id_profesional", nullable = false, length = 30)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)) })
	public JornadaId getId() {
		return this.id;
	}

	public void setId(JornadaId id) {
		this.id = id;
	}

}
