package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JornadaId generated by hbm2java
 */
@Embeddable
public class JornadaId implements java.io.Serializable {

	private String idProfesional;
	private int idLocalidad;
	private Date fecha;
	private Date horaInicio;
	private Date horaFin;
	private String descripcion;
	private int duracionCitas;
	private double duracionDesplazamiento;
	private double precio;

	public JornadaId() {
	}

	public JornadaId(String idProfesional, int idLocalidad, Date fecha, Date horaInicio, Date horaFin,
			String descripcion, int duracionCitas, double duracionDesplazamiento, double precio) {
		this.idProfesional = idProfesional;
		this.idLocalidad = idLocalidad;
		this.fecha = fecha;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.descripcion = descripcion;
		this.duracionCitas = duracionCitas;
		this.duracionDesplazamiento = duracionDesplazamiento;
		this.precio = precio;
	}

	@Column(name = "id_profesional", nullable = false, length = 30)
	public String getIdProfesional() {
		return this.idProfesional;
	}

	public void setIdProfesional(String idProfesional) {
		this.idProfesional = idProfesional;
	}

	@Column(name = "id_localidad", nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora_inicio", nullable = false, length = 19)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "hora_fin", nullable = false, length = 19)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "duracion_citas", nullable = false)
	public int getDuracionCitas() {
		return this.duracionCitas;
	}

	public void setDuracionCitas(int duracionCitas) {
		this.duracionCitas = duracionCitas;
	}

	@Column(name = "duracion_desplazamiento", nullable = false, precision = 22, scale = 0)
	public double getDuracionDesplazamiento() {
		return this.duracionDesplazamiento;
	}

	public void setDuracionDesplazamiento(double duracionDesplazamiento) {
		this.duracionDesplazamiento = duracionDesplazamiento;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JornadaId))
			return false;
		JornadaId castOther = (JornadaId) other;

		return ((this.getIdProfesional() == castOther.getIdProfesional())
				|| (this.getIdProfesional() != null && castOther.getIdProfesional() != null
						&& this.getIdProfesional().equals(castOther.getIdProfesional())))
				&& (this.getIdLocalidad() == castOther.getIdLocalidad())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getHoraInicio() == castOther.getHoraInicio()) || (this.getHoraInicio() != null
						&& castOther.getHoraInicio() != null && this.getHoraInicio().equals(castOther.getHoraInicio())))
				&& ((this.getHoraFin() == castOther.getHoraFin()) || (this.getHoraFin() != null
						&& castOther.getHoraFin() != null && this.getHoraFin().equals(castOther.getHoraFin())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& (this.getDuracionCitas() == castOther.getDuracionCitas())
				&& (this.getDuracionDesplazamiento() == castOther.getDuracionDesplazamiento())
				&& (this.getPrecio() == castOther.getPrecio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfesional() == null ? 0 : this.getIdProfesional().hashCode());
		result = 37 * result + this.getIdLocalidad();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getHoraInicio() == null ? 0 : this.getHoraInicio().hashCode());
		result = 37 * result + (getHoraFin() == null ? 0 : this.getHoraFin().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + this.getDuracionCitas();
		result = 37 * result + (int) this.getDuracionDesplazamiento();
		result = 37 * result + (int) this.getPrecio();
		return result;
	}

}
