package com.itinerant.entity;
// Generated 26 ene 2023 10:48:55 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JornadaId generated by hbm2java
 */
@Embeddable
public class JornadaId implements java.io.Serializable {

	private String idProfesional;
	private Date fecha;

	public JornadaId() {
	}

	public JornadaId(String idProfesional, Date fecha) {
		this.idProfesional = idProfesional;
		this.fecha = fecha;
	}

	@Column(name = "id_profesional", nullable = false, length = 30)
	public String getIdProfesional() {
		return this.idProfesional;
	}

	public void setIdProfesional(String idProfesional) {
		this.idProfesional = idProfesional;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JornadaId))
			return false;
		JornadaId castOther = (JornadaId) other;

		return ((this.getIdProfesional() == castOther.getIdProfesional())
				|| (this.getIdProfesional() != null && castOther.getIdProfesional() != null
						&& this.getIdProfesional().equals(castOther.getIdProfesional())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfesional() == null ? 0 : this.getIdProfesional().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
