package com.itinerant.entity;
// Generated 26 ene 2023 18:37:14 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SerieJornadasId generated by hbm2java
 */
@Embeddable
public class SerieJornadasId implements java.io.Serializable {

	private Integer idSerie;
	private Date fecha;

	public SerieJornadasId() {
	}

	public SerieJornadasId(Integer idSerie, Date fecha) {
		this.idSerie = idSerie;
		this.fecha = fecha;
	}

	@Column(name = "id_serie", nullable = false)
	public Integer getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(Integer idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SerieJornadasId))
			return false;
		SerieJornadasId castOther = (SerieJornadasId) other;

		return (this.getIdSerie() == castOther.getIdSerie())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSerie();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
