package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Supervisor generated by hbm2java
 */
@Entity
@NamedQueries({
	 @NamedQuery(name = "Supervisor.findAll", query = "SELECT s FROM Supervisor s ORDER BY s.apellidos"),
	 @NamedQuery(name = "Supervisor.countAll", query = "SELECT count(*) FROM Supervisor s"),
})
@Table(name = "supervisor", catalog = "itinerant_db")
public class Supervisor extends UsuarioPrivilegiado implements java.io.Serializable {

	private String nivelAcceso;

	public Supervisor() {
	}

	public Supervisor(String login, String password, String email, String nombre,String apellidos, 
			Date fechaNac, String telefono, String nss,String organismoCoordinador, String nivelAcceso) {
		super(login, password, email, nombre, apellidos, fechaNac, telefono, nss, organismoCoordinador);
		this.nivelAcceso = nivelAcceso;
	}
	
	public Supervisor(String login, String password, String email, String nombre,String apellidos, 
			Date fechaNac, String telefono, String nss,String organismoCoordinador, String nivelAcceso,
			byte[] fotoPerfil, Set<Chat> chatsForUsuarioFuente,Set<Alerta> alertas, 
			Set<Chat> chatsForUsuarioDestino) {
		super(login, password, email, nombre, apellidos, fechaNac, telefono, nss, organismoCoordinador,
				fotoPerfil, chatsForUsuarioFuente, alertas, chatsForUsuarioDestino);
		this.nivelAcceso = nivelAcceso;
	}

	@Column(name = "nivel_acceso", nullable = false, length = 10)
	public String getNivelAcceso() {
		return this.nivelAcceso;
	}

	public void setNivelAcceso(String nivelAcceso) {
		this.nivelAcceso = nivelAcceso;
	}

}
