package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VisitaPalabraClaveId generated by hbm2java
 */
@Embeddable
public class VisitaPalabraClaveId implements java.io.Serializable {

	private String idProfesional;
	private int idLocalidad;
	private Date fecha;
	private String palabraClave;

	public VisitaPalabraClaveId() {
	}

	public VisitaPalabraClaveId(String idProfesional, int idLocalidad, Date fecha, String palabraClave) {
		this.idProfesional = idProfesional;
		this.idLocalidad = idLocalidad;
		this.fecha = fecha;
		this.palabraClave = palabraClave;
	}

	@Column(name = "id_profesional", nullable = false, length = 30)
	public String getIdProfesional() {
		return this.idProfesional;
	}

	public void setIdProfesional(String idProfesional) {
		this.idProfesional = idProfesional;
	}

	@Column(name = "id_localidad", nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "palabra_clave", nullable = false, length = 20)
	public String getPalabraClave() {
		return this.palabraClave;
	}

	public void setPalabraClave(String palabraClave) {
		this.palabraClave = palabraClave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VisitaPalabraClaveId))
			return false;
		VisitaPalabraClaveId castOther = (VisitaPalabraClaveId) other;

		return ((this.getIdProfesional() == castOther.getIdProfesional())
				|| (this.getIdProfesional() != null && castOther.getIdProfesional() != null
						&& this.getIdProfesional().equals(castOther.getIdProfesional())))
				&& (this.getIdLocalidad() == castOther.getIdLocalidad())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getPalabraClave() == castOther.getPalabraClave())
						|| (this.getPalabraClave() != null && castOther.getPalabraClave() != null
								&& this.getPalabraClave().equals(castOther.getPalabraClave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfesional() == null ? 0 : this.getIdProfesional().hashCode());
		result = 37 * result + this.getIdLocalidad();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getPalabraClave() == null ? 0 : this.getPalabraClave().hashCode());
		return result;
	}

}
