package com.itinerant.entity;
// Generated 5 jul 2022 14:47:27 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * VisitaPalabraClave generated by hbm2java
 */
@Entity
@NamedQueries({
	 @NamedQuery(name = "VisitaPalabraClave.findAll", query = "SELECT pc FROM VisitaPalabraClave pc"),
	 @NamedQuery(name = "VisitaPalabraClave.countAll", query = "SELECT count(*) FROM VisitaPalabraClave pc"),
})
@Table(name = "visita_palabra_clave", catalog = "itinerant_db")
public class VisitaPalabraClave implements java.io.Serializable {

	private VisitaPalabraClaveId id;
	private Visita visita;

	public VisitaPalabraClave() {
	}

	public VisitaPalabraClave(VisitaPalabraClaveId id, Visita visita) {
		this.id = id;
		this.visita = visita;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProfesional", column = @Column(name = "id_profesional", nullable = false, length = 30)),
			@AttributeOverride(name = "idLocalidad", column = @Column(name = "id_localidad", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 10)),
			@AttributeOverride(name = "palabraClave", column = @Column(name = "palabra_clave", nullable = false, length = 20)) })
	public VisitaPalabraClaveId getId() {
		return this.id;
	}

	public void setId(VisitaPalabraClaveId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_profesional", referencedColumnName = "id_profesional", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_localidad", referencedColumnName = "id_localidad", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "fecha", referencedColumnName = "fecha", nullable = false, insertable = false, updatable = false) })
	public Visita getVisita() {
		return this.visita;
	}

	public void setVisita(Visita visita) {
		this.visita = visita;
	}

}
